// packages/vue/src/components/DiscordReactions.vue
<template>
  <div class="discord-reactions">
    <slot></slot>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({
    name: 'DiscordReactions',
  })
</script>

<style src="@discord-components/core/dist/styles/discord-reactions.scss"></style>

// packages/react/src/components/DiscordReactions.tsx
import React, { ReactElement } from 'react'
import { PropsWithSlot } from '../util'
import '@discord-components/core/dist/styles/discord-reactions.scss'

export default function DiscordReactions({ children }: PropsWithSlot): ReactElement {
  return <div className="discord-reactions">{children}</div>
}
