// packages/vue/src/components/DiscordMessage.vue
<template>
  <div
    class="discord-message"
    :class="{
      'discord-ephemeral-highlight': ephemeralMessage,
      'discord-mention-highlight': highlightMessage && !ephemeralMessage,
    }"
  >
    <slot name="interactions"></slot>
    <div class="discord-message-content">
      <div class="discord-author-avatar">
        <img :src="user.avatar" alt="" />
      </div>
      <div class="discord-message-body">
        <div v-if="!compactMode">
          <author-info :author="user.author" :bot="user.bot" :role-color="user.roleColor" />
          <span class="discord-message-timestamp">
            {{ messageTimestamp }}
          </span>
        </div>
        <template v-else>
          <span class="discord-message-timestamp">
            {{ messageTimestamp }}
          </span>
          <author-info :author="user.author" :bot="user.bot" :role-color="user.roleColor" />
        </template>
        <slot></slot>
        <span v-if="edited" class="discord-message-edited">(edited)</span>
        <slot name="embeds"></slot>
        <slot name="actions"></slot>
        <div v-if="ephemeralMessage" class="discord-message-ephemeral-notice">Only you can see this</div>
        <slot name="reactions"></slot>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import { computed, defineComponent, inject, toRefs } from 'vue'
  import { util } from '@discord-components/core'
  import { Profile, resolveOptions } from '../options'
  import AuthorInfo from './AuthorInfo.vue'

  export default defineComponent({
    name: 'DiscordMessage',
    components: {
      AuthorInfo,
    },
    props: {
      author: String,
      avatar: String,
      bot: {
        type: Boolean,
        default: null,
      },
      edited: Boolean,
      profile: String,
      roleColor: String,
      timestamp: {
        type: [Date, String],
        default: util.defaultTimestamp,
      },
    },
    setup(props, { slots }) {
      const options = resolveOptions()
      const { author, avatar, bot, profile: profileKey, roleColor, timestamp } = toRefs(props)
      const compactMode = inject('compactMode')

      const profile: Profile = !profileKey?.value ? {} : options.profiles?.[profileKey?.value] ?? {}
      const user: Profile = {
        author: !author?.value && profile?.author ? profile.author : author?.value || 'User',
        avatar: util.resolveImage(options.avatars, avatar?.value || profile?.avatar),
        bot: bot.value ?? profile?.bot,
        roleColor: roleColor?.value || profile?.roleColor,
      }

      const ephemeralMessage = computed(() => {
        return slots.interactions?.().some((slot) => slot?.props?.ephemeral)
      })

      const highlightMessage = computed(() => {
        return (
          slots.default?.().some((slot) => slot?.props?.highlight && slot?.props?.type !== 'channel') ||
          slots.interactions?.().some((slot) => slot?.props?.highlight)
        )
      })

      const messageTimestamp = computed(() => {
        return util.parseTimestamp({
          timestamp: timestamp.value,
          format: compactMode ? 'compact' : 'cozy',
        })
      })

      return {
        compactMode,
        ephemeralMessage,
        highlightMessage,
        messageTimestamp,
        user,
      }
    },
  })
</script>

<style src="@discord-components/core/dist/styles/discord-message.scss"></style>

// packages/react/src/components/DiscordMessage.tsx
import React, { Fragment, PropsWithChildren, ReactElement, ReactNode, isValidElement, useContext } from 'react'
import { util } from '@discord-components/core'
import { elementsWithoutSlot, findSlot } from '../util'
import DiscordDefaultOptions, { DiscordMessageOptions, Profile } from '../context/DiscordDefaultOptions'
import DiscordOptionsContext from '../context/DiscordOptionsContext'
import AuthorInfo from './AuthorInfo'
import '@discord-components/core/dist/styles/discord-message.scss'

export type DiscordMessageProps = PropsWithChildren<{
  author?: string
  avatar?: string
  bot?: boolean
  edited?: boolean
  profile?: string
  roleColor?: string
  timestamp?: Date | string
}>

export default function DiscordMessage({
  author,
  avatar,
  bot,
  children,
  compactMode,
  edited,
  profile: profileKey,
  roleColor,
  timestamp = util.defaultTimestamp,
}: DiscordMessageProps & { compactMode?: boolean }): ReactElement {
  const options: DiscordMessageOptions = useContext(DiscordOptionsContext) ?? DiscordDefaultOptions

  const profile: Profile = !profileKey ? {} : options.profiles?.[profileKey] ?? {}
  const user: Profile = {
    author: !author && profile?.author ? profile.author : author || 'User',
    avatar: util.resolveImage(options.avatars, avatar || profile?.avatar),
    bot: bot ?? profile?.bot,
    roleColor: roleColor || profile?.roleColor,
  }

  const messageTimestamp = util.parseTimestamp({
    timestamp,
    format: compactMode ? 'compact' : 'cozy',
  })

  const slots = {
    default: children,
    actions: findSlot(children, 'actions'),
    embeds: findSlot(children, 'embeds'),
    interactions: findSlot(children, 'interactions'),
    reactions: findSlot(children, 'reactions'),
  }

  if (slots.actions) {
    if (!isValidElement(slots.actions)) {
      throw new Error('Element with slot name "actions" should be a valid DiscordButtons component.')
    }

    slots.default = elementsWithoutSlot(slots.default, 'actions')
  }

  if (slots.embeds) {
    if (!isValidElement(slots.embeds)) {
      throw new Error('Element with slot name "embeds" should be a valid DiscordEmbed component.')
    }

    slots.default = elementsWithoutSlot(slots.default, 'embeds')
  }

  if (slots.interactions) {
    if (!isValidElement(slots.interactions)) {
      throw new Error('Element with slot name "interactions" should be a valid DiscordInteraction component.')
    }

    slots.default = elementsWithoutSlot(slots.default, 'interactions')
  }

  if (slots.reactions) {
    if (!isValidElement(slots.reactions)) {
      throw new Error('Element with slot name "reactions" should be a valid DiscordEmbed component.')
    }

    slots.default = elementsWithoutSlot(slots.default, 'reactions')
  }

  const ephemeralMessage = (slots?.interactions as ReactElement)?.props?.ephemeral

  const highlightMessage =
    (slots?.default as ReactElement[])?.some?.(({ props = {} }) => props?.highlight && props?.type !== 'channel') ||
    (slots?.interactions as ReactElement)?.props?.highlight

  let messageClasses = 'discord-message'
  if (ephemeralMessage) messageClasses += ' discord-ephemeral-highlight'
  if (highlightMessage && !ephemeralMessage) messageClasses += ' discord-mention-highlight'

  return (
    <div className={messageClasses}>
      {slots.interactions}
      <div className="discord-message-content">
        <div className="discord-author-avatar">
          <img src={user.avatar} alt="" />
        </div>
        <div className="discord-message-body">
          {!compactMode ? (
            <div>
              <AuthorInfo author={user.author} bot={user.bot} roleColor={user.roleColor} />
              <span className="discord-message-timestamp">{messageTimestamp}</span>
            </div>
          ) : (
            <Fragment>
              <span className="discord-message-timestamp">{messageTimestamp}</span>
              <AuthorInfo author={user.author} bot={user.bot} roleColor={user.roleColor} />
            </Fragment>
          )}
          {slots.default}
          {edited && <span className="discord-message-edited">(edited)</span>}
          {slots.embeds}
          {slots.actions}
          {ephemeralMessage && <div className="discord-message-ephemeral-notice">Only you can see this</div>}
          {slots.reactions}
        </div>
      </div>
    </div>
  )
}
