// packages/vue/src/components/DiscordEmbedFields.vue
<template>
  <div class="discord-embed-fields">
    <slot></slot>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({
    name: 'DiscordEmbedFields',
  })
</script>

<style src="@discord-components/core/dist/styles/discord-embed-fields.scss"></style>

// packages/react/src/components/DiscordEmbedFields.tsx
import React, { ReactElement } from 'react'
import { PropsWithSlot } from '../util'
import '@discord-components/core/dist/styles/discord-embed-fields.scss'

export default function DiscordEmbedFields({ children }: PropsWithSlot): ReactElement {
  return <div className="discord-embed-fields">{children}</div>
}
