// packages/vue/src/components/DiscordEmbedField.vue
<template>
  <div class="discord-embed-field" :class="{ 'discord-embed-field-inline': inline }">
    <div class="discord-embed-field-title">
      {{ fieldTitle }}
    </div>
    <slot></slot>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({
    name: 'DiscordEmbedField',
    props: {
      fieldTitle: {
        type: String,
        required: true,
      },
      inline: Boolean,
    },
  })
</script>

<style src="@discord-components/core/dist/styles/discord-embed-field.scss"></style>

// packages/react/src/components/DiscordEmbedField.tsx
import React, { PropsWithChildren, ReactElement } from 'react'
import '@discord-components/core/dist/styles/discord-embed-field.scss'

export type DiscordEmbedFieldProps = PropsWithChildren<{
  inline?: boolean
  fieldTitle: string
}>

export default function DiscordEmbedField({ children, inline, fieldTitle }: DiscordEmbedFieldProps): ReactElement {
  let classes = 'discord-embed-field'
  if (inline) classes += ' discord-embed-field-inline'

  return (
    <div className={classes}>
      <div className="discord-embed-field-title">{fieldTitle}</div>
      {children}
    </div>
  )
}
