// packages/vue/src/components/DiscordEmbed.vue
<template>
  <div class="discord-embed">
    <div class="discord-embed-left-border" :style="{ 'background-color': borderColor }"></div>
    <div class="discord-embed-container">
      <div class="discord-embed-content">
        <div>
          <div v-if="authorName" class="discord-embed-author">
            <img v-if="authorIcon" class="discord-embed-author-icon" :src="authorIcon" alt="" />
            <a v-if="authorUrl" :href="authorUrl" target="_blank" rel="noopener noreferrer">
              {{ authorName }}
            </a>
            <span v-else>
              {{ authorName }}
            </span>
          </div>
          <div v-if="embedTitle" class="discord-embed-title">
            <a v-if="url" :href="url" target="_blank" rel="noopener noreferrer">
              {{ embedTitle }}
            </a>
            <span v-else>
              {{ embedTitle }}
            </span>
          </div>
          <div class="discord-embed-description">
            <slot></slot>
          </div>
          <slot name="fields"></slot>
          <img v-if="image" class="discord-embed-image" :src="image" alt="" />
        </div>
        <img v-if="thumbnail" class="discord-embed-thumbnail" :src="thumbnail" alt="" />
      </div>
      <div v-if="$slots.footer || timestamp" class="discord-embed-footer">
        <img v-if="$slots.footer && footerIcon" class="discord-embed-footer-icon" :src="footerIcon" alt="" />
        <span>
          <slot name="footer"></slot>
          <span v-if="$slots.footer && timestamp" class="discord-embed-footer-separator">&bull;</span>
          <span v-if="timestamp">
            {{ parseTimestamp({ timestamp }) }}
          </span>
        </span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'
  import { util } from '@discord-components/core'

  export default defineComponent({
    name: 'DiscordEmbed',
    props: {
      authorIcon: String,
      authorName: String,
      authorUrl: String,
      borderColor: String,
      embedTitle: String,
      footerIcon: String,
      image: String,
      thumbnail: String,
      timestamp: [Date, String],
      url: String,
    },
    setup(props, { slots }) {
      return {
        parseTimestamp: util.parseTimestamp,
      }
    },
  })
</script>

// packages/react/src/components/DiscordEmbed.tsx
import React, { ReactElement, isValidElement } from 'react'
import { util } from '@discord-components/core'
import { PropsWithSlot, elementsWithoutSlot, findSlot } from '../util'

export type DiscordEmbedProps = {
  authorIcon?: string
  authorName?: string
  authorUrl?: string
  borderColor?: string
  embedTitle?: string
  image?: string
  footerIcon?: string
  thumbnail?: string
  timestamp?: Date | string
  url?: string
}

export default function DiscordEmbed({
  authorIcon,
  authorName,
  authorUrl,
  children,
  borderColor,
  embedTitle,
  footerIcon,
  image,
  thumbnail,
  timestamp,
  url,
}: DiscordEmbedProps & PropsWithSlot): ReactElement {
  const slots = {
    default: children,
    fields: findSlot(children, 'fields'),
    footer: findSlot(children, 'footer'),
  }

  if (slots.fields) {
    if (!isValidElement(slots.fields)) {
      throw new Error('Element with slot name "fields" should be a valid DiscordEmbedFields component.')
    }

    slots.default = elementsWithoutSlot(slots.default, 'fields')
  }

  if (slots.footer) slots.default = elementsWithoutSlot(slots.default, 'footer')

  const content = {
    author: (
      <div className="discord-embed-author">
        {authorIcon && <img className="discord-embed-author-icon" src={authorIcon} alt="" />}
        {authorUrl ? (
          <a href={authorUrl} target="_blank" rel="noopener noreferrer">
            {authorName}
          </a>
        ) : (
          <span>{authorName}</span>
        )}
      </div>
    ),
    footer: (
      <div className="discord-embed-footer">
        {slots.footer && footerIcon && <img className="discord-embed-footer-icon" src={footerIcon} alt="" />}
        <span>
          {slots.footer}
          {slots.footer && timestamp && <span className="discord-embed-footer-separator">&bull;</span>}
          {timestamp && <span>{util.parseTimestamp({ timestamp })}</span>}
        </span>
      </div>
    ),
    title: (
      <div className="discord-embed-title">
        {url ? (
          <a href={url} target="_blank" rel="noopener noreferrer">
            {embedTitle}
          </a>
        ) : (
          <span>{embedTitle}</span>
        )}
      </div>
    ),
  }

  return (
    <div className="discord-embed">
      <div className="discord-embed-left-border" style={{ backgroundColor: borderColor }}></div>
      <div className="discord-embed-container">
        <div className="discord-embed-content">
          <div>
            {authorName && content.author}
            {embedTitle && content.title}
            <div className="discord-embed-description">{slots.default}</div>
            {slots.fields}
            {image && <img className="discord-embed-image" src={image} alt="" />}
          </div>
          {thumbnail && <img className="discord-embed-thumbnail" src={thumbnail} alt="" />}
        </div>
        {(slots.footer || timestamp) && content.footer}
      </div>
    </div>
  )
}
