// packages/react/src/components/DiscordMarkdown.tsx
import React, { Children, ReactElement, ReactNode } from 'react'
import { util } from '@discord-components/core'
import '@discord-components/core/dist/styles/discord-markdown.scss'

export default function DiscordMarkdown({ children }: { children?: ReactNode }): ReactElement {
  const parsedContent = Children.map(
    children as ReactElement[],
    (child: ReactNode): ReactNode => {
      if (typeof child !== 'string' || !child.length) return child
      return <span className="discord-markdown-content" dangerouslySetInnerHTML={{ __html: util.markdownParser.toHTML(child) }}></span>
    },
  )

  return <span className="discord-markdown">{parsedContent}</span>
}

// packages/vue/src/components/DiscordMarkdown.vue
<script lang="ts">
  import { VNode, defineComponent, h } from 'vue'
  import { util } from '@discord-components/core'

  export default defineComponent({
    name: 'DiscordMarkdown',
    setup(props, { slots }) {
      return (): VNode => {
        const parsedContent = slots.default?.().map(
          (vNode: VNode): VNode => {
            if (typeof vNode.children !== 'string' || !vNode.children.length) return vNode
            return h('span', {
              class: 'discord-markdown-content',
              innerHTML: util.markdownParser.toHTML(vNode.children),
            })
          },
        )

        return h(
          'span',
          { class: 'discord-markdown' },
          {
            default: () => parsedContent,
          },
        )
      }
    },
  })
</script>

<style src="@discord-components/core/dist/styles/discord-markdown.scss"></style>
